config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resource :session, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :show, :index, :edit, :update]
  resources :photos, only: [:create, :index]
  resources :events, only: [:index] do
    collection do
      post 'set_timezone'
    end
  end

  get 'feed' => 'posts#feed', as: 'posts_feed', format: 'rss'
  get 'posts/page/:page' => 'posts#page', as: 'posts_page'
  get 'about' => 'pages#about', as: 'about'
  post 'send_contact' => 'pages#send_contact', as: 'send_contact'

  namespace :api , defaults: { format: :json } do
    resource :session, only: [:show, :create, :destroy]
    resources :posts, only: [:show, :index]
    post 'send_contact' => 'pages#send_contact', as: 'send_contact'
  end

  get '*path' => redirect('/') #if Rails.env.production?
end

app/views/layouts/_flash.html.haml
- if flash[:notice] || flash[:error] || flash[:alert]
  .row#flash.collapsed.in{ class: flash_class }
    .col-xs-12.text-center
      = flash[:notice] || flash[:error] || flash[:alert]
      .pull-right= link_to ('&#x2715;').html_safe, '#flash', 'data-toggle' => 'collapse'

app/views/layouts/_navigation.html.haml
.row.navigation
  = render partial: 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
.inner-nav
  %ul
    %li= link_to 'Home', root_path
    %li= link_to 'About', about_path
    %li= link_to 'Contact', contact_path
    - if current_user
      %li= link_to 'Photos', photos_path
      %li= link_to 'Events', events_path
      %li= link_to 'New Post', new_post_path

app/views/layouts/_sidebar.html.haml
.item.white-box
  = image_tag('https://dl.dropboxusercontent.com/u/2330299/blog/design/2016-07-19-profile.png', class: 'profile-pic')
  = "Hello! I'm Karen and Twinkie is my furry best friend!"
.item.white-box
  .social-media
    = link_to icon('linkedin'), 'https://www.linkedin.com/in/karensling', target: '_blank'
    = link_to icon('github'), 'https://github.com/karenling', target: '_blank'
    = link_to icon('instagram'), 'https://www.instagram.com/hellotwinkie/', target: '_blank'
    = link_to icon('envelope'), contact_path, target: '_blank'
    = link_to icon('rss'), posts_feed_path, target: '_blank'
.item.white-box
  .title Tags
  .all-tags
    = display_tag_cloud

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @title ? "Twinkie and Karen | #{@title}" : "Twinkie and Karen"
    %link{href: "https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i",
          rel: "stylesheet",
          type: "text/css"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
%body
  .container-fluid
    = render partial: 'layouts/flash'
    .row
      = yield


:javascript
  window.profile_url = "#{image_url('profile.jpg')}"
- if @session_timezone.blank?
  :javascript
    TwinkieandKaren.setTimezone();

app/views/layouts/without_react.html.haml
!!!
%html
  %head
    %title= @title ? "Twinkie and Karen | #{@title}" : "Twinkie and Karen"
    %link{:href => "//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/

%body
  = yield

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-4234175-15', 'auto');
  ga('send', 'pageview');